name: ci-bun

on:
    push:
        branches:
            - main
            - "release/*/v**"

    pull_request:
        branches:
            - main
            - "release/*/v**"

jobs:
    ci-bun:
        uses: eslint/workflows/.github/workflows/ci-bun.yml@main
