name: ci-package-manager

on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - main

jobs:
    ci-package-manager:
        # Skip on Release Please PRs and when that PR is merged to main.
        # https://github.com/eslint/rewrite/issues/366
        if: >-
            !(github.event_name == 'pull_request' && github.event.pull_request.user.login == 'eslintbot' && contains(github.event.pull_request.title, 'chore: release'))
            && !(
              github.event_name == 'push'
              && github.ref_name == 'main'
              && (
                contains(github.event.head_commit.message, 'chore: release')
                && contains(github.event.head_commit.author.username, 'eslintbot')
              )
            )
        uses: eslint/workflows/.github/workflows/ci-package-manager.yml@main
