on:
    push:
        branches:
            - main

name: release-please

permissions:
    contents: write
    pull-requests: write
    id-token: write

jobs:
    release-please:
        runs-on: ubuntu-latest
        steps:
            - uses: googleapis/release-please-action@v4
              id: release
              with:
                  token: ${{secrets.GITHUB_TOKEN}}

            # Output which releases were created
            - name: Output release info
              run: |
                  echo "releases_created:" ${{ steps.release.outputs.releases_created }}
                  echo "packages/compat--release_created:" ${{ steps.release.outputs['packages/compat--release_created'] }}
                  echo "packages/config-array--release_created" ${{ steps.release.outputs['packages/config-array--release_created'] }}
                  echo "packages/core--release_created" ${{ steps.release.outputs['packages/core--release_created'] }}
                  echo "packages/migrate-config--release_created" ${{ steps.release.outputs['packages/migrate-config--release_created'] }}
                  echo "packages/object-schema--release_created:" ${{ steps.release.outputs['packages/object-schema--release_created'] }}
                  echo "packages/plugin-kit--release_created" ${{ steps.release.outputs['packages/plugin-kit--release_created'] }}

            # Check to see if we need to do any releases and if so check out the repo
            - uses: actions/checkout@v5
              if: ${{ steps.release.outputs.releases_created == 'true' }}

            # Node.js release
            - uses: actions/setup-node@v4
              if: ${{ steps.release.outputs.releases_created == 'true' }}
              with:
                  node-version: lts/*
                  registry-url: "https://registry.npmjs.org"

            - run: |
                  npm install
                  npm run build
              if: ${{ steps.release.outputs.releases_created == 'true' }}

            #-----------------------------------------------------------------------------
            # NOTE: This script currently doesn't do anything. It just outputs the
            # release information to the console. We will do this for a few releases
            # to make sure everything is working correctly before we switch to use this
            # script exclusively.
            #-----------------------------------------------------------------------------

            - name: Publish using new script
              run: node scripts/publish.js
              if: ${{ steps.release.outputs.releases_created == 'true' }}
              env:
                  STEPS_RELEASE_OUTPUTS: ${{ toJson(steps.release.outputs) }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                  TWITTER_API_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
                  TWITTER_API_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
                  TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
                  TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
                  MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
                  MASTODON_HOST: ${{ secrets.MASTODON_HOST }}
                  BLUESKY_IDENTIFIER: ${{ vars.BLUESKY_IDENTIFIER }}
                  BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
                  BLUESKY_HOST: ${{ vars.BLUESKY_HOST }}
